### ISSUE TITLE
Should we define some emoji for use in commits?

### ISSUE THREAD

**Issue by codewitchio** [Zalodu/Schedutalk#12]
It could help with clarity if we use them in commits, but we have to keep it consistent if we do, and if so add them to `CONTRIBUTING.md`.

Like for example :bug: for bugs, or :fire: for when the servers are on fire etc.

**Comment by EricLewe** [comment]
Sounds like a great idea would you mind deciding what we should use? I suggest the following
:bug: for bugs
:memo: for docing
:thought_balloon: for suggestion
:dart: for target related things (target is in this case the android and lumia phone)
:open_file_folder: for moving around code between fodlers etc

**Comment by codewitchio** [comment]
I'll get to writing these down in the `CONTRIBUTING.md` specifications when I get home!
