### ISSUE TITLE
Spec out the MVP!

### ISSUE THREAD

**Issue by macaullyjames** [Zalodu/Schedutalk#14]
So there's a few bits and pieces in the repo about what it is you're working on, but it would be nice if you could flesh out the MVP in an issue. I humbly suggest creating a new issue for discussion, and keep editing the first post so that there's always an up-to-date summary at the top of the thread.

Kind of like https://github.com/xobust/Project-Broban/issues/1 :)

**Comment by EricLewe** [comment]
See #15 hopefully I understand what MVP stands for, ehm Mac what does it really stand for? xD

**Comment by codewitchio** [comment]
@EE87 [Minimum Viable Product](https://en.wikipedia.org/wiki/Minimum_viable_product), as referenced in [Mac's inda guidelines](https://github.com/macaullyjames/inda-project-guidelines).

**Comment by macaullyjames** [comment]
![image](https://cloud.githubusercontent.com/assets/3997058/15112338/c0537086-15ed-11e6-81b3-f222b7ec81a1.jpeg)
