### ISSUE TITLE
KTH places API integration

### ISSUE THREAD

**Issue by codewitchio** [Zalodu/Schedutalk#24]
Could allow users to click on the location of an event to link to the KTH places map etc.

**Comment by codewitchio** [comment]
[Here](https://www.kth.se/api/places/swagger/?url=/api/places/swagger.json#/__v3)'s the specifications for the KTH places API.

**Comment by EricLewe** [comment]
I have recieved a mail from the IT Administration at KTH, we need a key from them inorder to use their API, this is to ensure that we get notified if there are changes occuring in the API in order to secure our own code from being :bug: . However they said we will recieve the key this week. So we will see if it gets there on time.

**Comment by codewitchio** [comment]
Alright, fingers crossed!

**Comment by EricLewe** [comment]
Just recieved the API key :+1:

**Comment by codewitchio** [comment]
Sweet! :+1:

**Comment by EricLewe** [comment]
Useful link for Http requests with JSON as the recieved data:
https://msdn.microsoft.com/en-us/library/hh674188.aspx
http://stackoverflow.com/questions/31825627/xamarin-forms-pcl-clean-and-easy-way-for-a-webrequest

**Comment by EricLewe** [comment]
The following data is useful for us to extract from webrequests:

GET /v3/room/name/{name}
If there is power outlets or not in the room
also the following fields:
floorUid
imageUrls
geodata
buildingName
campus
typeName
placeName
uid
id //Not sure if needed

GET /v3/room/exists/{id}
this is used to make sure the room specifed exists

GET /v3/room/id/{id}/freeSeats
is useful if we want to monitor computer labs spaces, perhaps possible to make lab scheduled things automatically display free seats

GET /v3/floorplan/{id}
get floor image, which I currently dont know what to pass in.

**Comment by EricLewe** [comment]
The principle is now implemented and addig future features are easily possible!
