### ISSUE TITLE
Add gitignore

### ISSUE THREAD

**Issue by codewitchio** [Zalodu/Schedutalk#26]
Simply opening visual studio and editing no files leads to this beautiful changelog: ![changes](http://puu.sh/p2frr/bbe23cd08d.png)

Maybe excluding everything from the `/Schedutalk/Schedutalk.{target}/obj/Debug` folders would be useful.

**Comment by EricLewe** [comment]
Definitley! Didnt have the time to fix it, assign this issue to me if you want me to have it fixed!

**Comment by codewitchio** [comment]
Hmm, I'm fixing it now but I just realized there's not only items from `/obj/Debug/`, but from for example `/bin/` in the droid target folder: ![image](http://puu.sh/p2gwb/8ee1554bd6.png)

Is it too much to just add all target folders to the gitignore or should that be fine since we didn't plan on editing those anyway?

**Comment by codewitchio** [comment]
Uh oh, Visual Studio is trying to find android files in _your_ home directory, I think personal IDE settings may be leaking into the repo because of the lack of gitignore :sob: ![Image](http://puu.sh/p2gLQ/34e615608a.png)

**Comment by codewitchio** [comment]
I'm gonna go ahead and just add [this gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) and see if I can salvage the user settings situation.

**Comment by EricLewe** [comment]
Ok I found a gitignore which is made for Viusal studio. Hopefully that ought to do it

**Comment by EricLewe** [comment]
Thats the one I thought about! Nice
