### ISSUE TITLE
Schedule control

### ISSUE THREAD

**Issue by codewitchio** [Zalodu/Schedutalk#4]
We need a schedule able to show when something in time starts and ends. A challenge may be that this requires native controls at the platforms.

**Comment by EricLewe** [comment]
![image](https://cloud.githubusercontent.com/assets/18601399/15013621/f35063b8-1200-11e6-970d-7a47420c4e45.png)

This is an idea of how this should look like.

**Comment by EricLewe** [comment]
Implemented and pushed.
