### ISSUE TITLE
Selectable calendar

### ISSUE THREAD

**Issue by codewitchio** [Zalodu/Schedutalk#6]
The next step is to make the calendar actually selectable, in that way we can assign more data linked to a certain event in the schedule. The features we want is a textbox and a rating, where the user can rate the event but also provide a comment.

Future ideas could be to make it possible to read and rate other users comments, so the most useful comments for an event gets saved. (This is however out of scope of this project)

**Comment by EricLewe** [comment]
This is succesfully implemented and will be pushed to master
